apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8sdeploy
  name: k8sdeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8sdeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8sdeploy
    spec:
      containers:
      - image: rajeshdulam/nodejs:latest
        name: nodejs
        resources: {}
status: {}
