apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8sdeploy
  name: k8sdeploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8sdeploy
status:
  loadBalancer: {}
